### PR TITLE
Revamping main activity

### PR DESCRIPTION
**Pull request by johnyukon21**
Revamping the dashboard/main screen
    * adding sync progress bar to the dashboard
    * changing the color of the switch to be green when ON
    * making the sync progress and the qr code appear in seperate cards for better readablity
    * changing the way the daemon status is displayed to reflect better to the user of what the app is trying to do
    * making the screen scrollable
    * support landscape view
    * fixes the issue of the QR code disappearing
    * changing the way the UI is refreshed so that the status reporting on the screen is more robust

Tested on Samsung Glaxy S9 with all three daemons

Screen Shot 2019-07-11 at 6 26 33 PM
Screen Shot 2019-07-11 at 6 26 53 PM
Screen Shot 2019-07-11 at 6 27 12 PM
Screen Shot 2019-07-11 at 6 27 35 PM
Screen Shot 2019-07-11 at 6 30 18 PM

### CODE REVIEW

**Comment by RCasatta** [comment]
In the Dashboard I would avoid repeating the info about the used package since it is already in the toolbar.
Instead of `Daemon: core 0.18.0` I would use: `Version: 0.18.0`

Probably I would hide the two cards in the MainActivity if they are empty

But this could be incremental improvements, ack 6399a70397d9676b6c16656b7a82eae3a8372aed

**Comment by johnyukon21** [comment]
> In the Dashboard I would avoid repeating the info about the used package since it is already in the toolbar.
> Instead of `Daemon: core 0.18.0` I would use: `Version: 0.18.0`
> 
> Probably I would hide the two cards in the MainActivity if they are empty
> 
> But this could be incremental improvements, ack [6399a70](https://github.com/greenaddress/abcore/commit/6399a70397d9676b6c16656b7a82eae3a8372aed)

Makes sense to me. I can get this out with the next PR. Thanks for looking!

**Comment by lvaccaro** [comment]
ack 6399a70397d9676b6c16656b7a82eae3a8372aed

nit: squash the UX improvements with removing stuff commits

**Comment by RCasatta** [comment]
merged with https://github.com/greenaddress/abcore/pull/85

**Pull request closed without merging**
