### PR TITLE
V0.18.1

### PR DESCRIPTION
**Pull request by greenaddress**
updates android, libraries and bitcoin/knots/liquid daemons

### CODE REVIEW

**Comment by greenaddress** [comment]
I think even if we merge this we can't release soon as there's a bunch of bugs in master to be dealt with

**Comment by greenaddress** [comment]
Attaching a signed RC



[RC.zip](https://github.com/greenaddress/abcore/files/3555812/RC.zip)

**Comment by greenaddress** [comment]
@johnyukon21

Do you want to give it a try/look? if there's no blockers we can release

**Comment by udiWertheimer** [comment]
ack 2726cc4

**Pull request merged**
